language: python
python:
    - 3.5
    - 3.6

install:
    - pip install -r requirements.txt
    - npm install package.json

script:
    - flake8 amsite
    - python manage.py test

sudo: false

notifications:
  email: false

matrix:
    fast_finish: true
