# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 20:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('state', models.CharField(default='in_progress', max_length=32)),
                ('estimate', models.DateField()),
                ('created', models.DateField(default=datetime.date.today, editable=False)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amsite.Roadmap')),
            ],
        ),
        migrations.AddField(
            model_name='scores',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='amsite.Task'),
        ),
    ]
